name: RevitalizeCore
version: '1.0'
main: de.peaqe.revitalizecore.RevitalizeCore
api-version: '1.21'
authors: [ peaqe ]

commands:
  # Main plugin
  repository:
    aliases:
      - repo
      - repos
      - repositories
  # Modules
  chatfilter:
    aliases:
      - filter
  playerinfo:
    aliases:
      - pi
      - info
      - spielerinfo
  coins:
